AutoPartsStore/AutoPartsStore/Models/CustomerCheckout.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ModelsLibrary;

namespace AutoPartsStore.Models
{
    public class CustomerCheckout
    {
        public IEnumerable<ModelsLibrary.Item> itemList { get; set; }
        public int StoreNum {get; set;}
        public Customer cust { get; set; }

    }
}

AutoPartsStore/AutoPartsStore/Models/ErrorViewModel.cs
using System;

namespace AutoPartsStore.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

AutoPartsStore/AutoPartsStore/Models/Item.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AutoPartsStore.Models
{
    public class Item
    {
        public int PartId { get; set; }
        public int PartNumber { get; set; }
        public string Part { get; set; }
        public string PartDescription { get; set; }
        public double Price { get; set; }
        public string PartLocation
        {
            get; set;
        }
    }
}

AutoPartsStore/AutoPartsStore/Models/Store.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AutoPartsStore.Models
{
    public class Store
    {

    }
}

AutoPartsStore/AutoPartsStore/Controllers/HomeController.cs
using AutoPartsStore.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace AutoPartsStore.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Welcome(string name, int numTimes = 1)
        {
            // Contains the data that will be passed to the view
            ViewData["Messages"] = "Hello " + name;
            ViewData["NumTimes"] = numTimes;

            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        /*
        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }*/
    }
}

AutoPartsStore/AutoPartsStore/Controllers/StoreController.cs
//using AutoPartsStore.Models;
using BusinessLayer;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using ModelsLibrary;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AutoPartsStore.Controllers
{
    public class StoreController : Controller
    {

        private readonly IApp _appStore;
        
        // create a constructor that will inject the business layer
        public StoreController(IApp appStore)
        {
            this._appStore = appStore;
        }

        // GET: Store
        public ActionResult Index()
        {
           // Customer cust = new Customer();
           /* {
                firstName = "John",
                lastName = "Smith",
                email = "jsmith@email.com"
            };*/
            return View();
        }

        // GET: Store/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Store/Create
        public ActionResult Create()
        {
            return View("CreateCustomer");
        }

        [HttpPost]
        public ActionResult CreateCustomer(Customer c)
        {
            if(!ModelState.IsValid)
            {
                RedirectToAction("Create");
            }
            return View("VerifyCreateCustomer", c);
        }

        [HttpPost]
        public async Task<ActionResult> CreateNewCustomer(Customer c)
        {
            if(!ModelState.IsValid)
            {
                RedirectToAction("Create");
            }

            bool register = await _appStore.RegisterCustomerAsync(c);
            
            if(register)
            {
                ViewBag.Welcome = "Welcoming Example With ViewBag";
                return View("VerifyCreateCustomer", c);
            }
            else
            {
                ViewBag.ErrorText = "Welcome Example With Error";
                return View("VerifyCreateCustomer");
            }

        }

        /*[HttpPost]
        public async Task<ActionResult> Select(Tuple<Store,Customer> tuple)
        {
            // display parts for store selected
           List<ModelsLibrary.Item> itemList = await _appStore.ItemListAsync(tuple.Item1);

            // change store for customer object
            bool changeStore = await _appStore.ChangeStore(tuple.Item1, tuple.Item2);

            if(changeStore)
            {
                return View("VerifyCreateCustomer", tuple.Item2);
            }
            else
            {
                return await Login(tuple.Item2.LastName, tuple.Item2.Password);
            }

            return View();
        }*/

/*        [HttpPost]
        public async Task<ActionResult> Select(int store)
        {

            Customer cust = new Customer();
            // display parts for store selected
            List<ModelsLibrary.Item> itemList = await _appStore.ItemListAsync(store);

            // change store for customer object
            bool changeStore = await _appStore.ChangeStore(store, cust);

            if (changeStore)
            {
                return View("VerifyCreateCustomer", cust);
            }
            else
            {
                return await Login(cust.LastName, cust.Password);
            }

            return View();
        }
*/
        // POST: Store/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        [HttpPost]
        public async Task<ActionResult> Login(string LastName, string Password)
        {

            Customer cust = await _appStore.FindCustomerAsync(LastName, Password);
            if(cust == null)
            {
                return View("../Home/Index");
            }
            else
            {
                // get list of stores
                List<Store> storeList = await _appStore.StoreListAsync();

                // return a view to allow customer to select store to shop from
                var tuple = new Tuple<List<Store>, Customer>(storeList, cust);

                   return View("CustomerLoggedIn", tuple);
            }
            /*
            return View();*/
        }

        // GET: Store/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Store/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: Store/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Store/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }


    }
}

AutoPartsStore/AutoPartsStore/Views/Home/Index.cshtml
@model ModelsLibrary.Customer
@{
    ViewData["Title"] = "Home Page";


}


<!-- Form to login with customer credentials-->

<div class="col-md-4">
    <form asp-action="Login" method="post">
        <div class="form-group">
            <label asp-for="LastName">Enter Last Name&nbsp;</label>
            <input type="text" id="lastName" name="LastName"/>
        </div>

        <div class="form-group">
            <label asp-for="Password">Enter Password&nbsp;&nbsp;&nbsp;</label>
            <input type="password" id="password" name="Password"/>
        </div>
        <div>
            <a class="btn-outline-primary" asp-area="" asp-controller="Store" asp-action="Create">Create an Account&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</a>
            <input type="submit" asp-controller="Store" asp-action="Login"/>
        </div>
        <input name="__RequestVerificationToken" type="hidden" value="token_generated_here" />
    </form>
</div>

AutoPartsStore/AutoPartsStore/Views/Home/Welcome.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Title"] = "Welcome";
}

<h2>Welcome</h2>

<ul>
    @for( int i = 0; i < (int)ViewData["NumTimes"]; i++)
            {
                <li>@ViewData["Messages"]</li>
            }
</ul>

AutoPartsStore/AutoPartsStore/Views/Item/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Title"] = "Item List";
}

<h2>Item List</h2>
<p>Hello from your Item View Template!</p>

<body>
    <div class="container">
        <a class="navbar-brand" asp-area="" asp-controller="Item" asp-action="StoreNums">Select Store</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
    </div>
</body>

AutoPartsStore/AutoPartsStore/Views/Item/ItemList.cshtml
@model IEnumerable<ModelsLibrary.Item>

@{
    ViewData["Title"] = "Item List";
}

<h1>Item List</h1>

<p>
    <a asp-controller = "Item" asp-action="Index">Back To Store List</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.PartNumber)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Part)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PartDesc)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Price)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Quantity)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Location)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Store)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.PartNumber)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Part)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PartDesc)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Price)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Quantity)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Location)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Store)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.PartId">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.PartId">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.PartId">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

AutoPartsStore/AutoPartsStore/Views/Item/StoreList.cshtml
@model IEnumerable<ModelsLibrary.Store>

@{
    ViewData["Title"] = "StoreList";
}

<h1>Select Store</h1>


<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.City)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.State)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PhoneNumber)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.City)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.State)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PhoneNumber)
            </td>
            <td>
                @Html.ActionLink("Select", "StoreInventory", item) |
                <a asp-action="Details" asp-route-id="@item.StoreId">Orders</a> |


            </td>
        </tr>
}
    </tbody>
</table>

AutoPartsStore/AutoPartsStore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Auto Parts Plus</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Item" asp-action="Index">Auto Parts Plus</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Auto Parts Plus - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

AutoPartsStore/AutoPartsStore/Views/Store/CreateCustomer.cshtml
@model ModelsLibrary.Customer

@{
    ViewData["Title"] = "CreateCustomer";
}

<h1>CreateCustomer</h1>

<h4>Customer</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="CreateNewCustomer">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            @*<div class="form-group">
            <label asp-for="CustomerId" class="control-label"></label>
            <input asp-for="CustomerId" class="form-control" />
            <span asp-validation-for="CustomerId" class="text-danger"></span>
        </div>*@
            <div class="form-group">
                <label asp-for="FirstName" class="control-label"></label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PhoneNumber" class="control-label"></label>
                <input asp-for="PhoneNumber" class="form-control" />
                <span asp-validation-for="PhoneNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CarYear" class="control-label"></label>
                <input asp-for="CarYear" class="form-control" />
                <span asp-validation-for="CarYear" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CarMake" class="control-label"></label>
                <input asp-for="CarMake" class="form-control" />
                <span asp-validation-for="CarMake" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CarModel" class="control-label"></label>
                <input asp-for="CarModel" class="form-control" />
                <span asp-validation-for="CarModel" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="City" class="control-label"></label>
                <input asp-for="City" class="form-control" />
                <span asp-validation-for="City" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="State" class="control-label"></label>
                <input asp-for="State" class="form-control" />
                <span asp-validation-for="State" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Password" class="control-label"></label>
                <input asp-for="Password" class="form-control" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Store" class="control-label"></label>
                <input asp-for="Store" class="form-control" />
                <span asp-validation-for="Store" class="text-danger"></span>
            </div>

            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

AutoPartsStore/AutoPartsStore/Views/Store/CustomerList.cshtml
@model IEnumerable<ModelsLibrary.Customer>

@{
    ViewData["Title"] = "CustomerList";
}

<h1>CustomerList</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.CustomerId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FirstName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.LastName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PhoneNumber)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Email)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.City)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.State)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Password)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Store)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CarYear)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CarMake)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CarModel)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.CustomerId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FirstName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LastName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PhoneNumber)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.City)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.State)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Password)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Store)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CarYear)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CarMake)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CarModel)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
            </td>
        </tr>
}
    </tbody>
</table>

AutoPartsStore/AutoPartsStore/Views/Store/CustomerLoggedIn.cshtml
@using ModelsLibrary
@model Tuple<List<ModelsLibrary.Store>, ModelsLibrary.Customer>



@{
    ViewData["Title"] = "CustomerLoggedIn";
}

<h1>Welcome @Html.DisplayFor(model => Model.Item2.FirstName)</h1>

<p>
    <strong>Car Year: </strong> @Html.DisplayFor(model => Model.Item2.CarYear)
    <strong>Car Make: </strong> @Html.DisplayFor(model => Model.Item2.CarMake)
    <strong>Car Model: </strong> @Html.DisplayFor(model => Model.Item2.CarModel)
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                Store Number
            </th>
            <th>
                City
            </th>
            <th>
                State
            </th>
            <th>
                PhoneNumber
            </th>
            <th>
                Choose Store
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.Item1)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.StoreId)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.City)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.State)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.PhoneNumber)
                    
                </td>
                <td>
                    @*@Html.ActionLink("Select", "Select", @item.StoreId)                 *@
                    <a asp-action="Select" asp-route-id="@item.StoreId">Select</a> |
                    <!--Details for store order history-->
                    <a asp-action="Details" asp-route-id="@item.StoreId">Details</a> |
                    
                </td>
            </tr>
        }
    </tbody>
</table>

AutoPartsStore/AutoPartsStore/Views/Store/Index.cshtml
@model ModelsLibrary.Customer

@{
    ViewData["Title"] = Model.FirstName + " - View";
}


<div>
    <h4>Customer Info</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @*   @Html.DisplayNameFor(model => model.firstName)*@
            First Name:
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.FirstName)
        </dd>
        <dt class="col-sm-2">
            @*@Html.DisplayNameFor(model => model.lastName)*@
            Last Name:
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.LastName)
        </dd>
        <dt class="col-sm-2">
            @*@Html.DisplayNameFor(model => model.phoneNumber)*@
            Phone:
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.PhoneNumber)
        </dd>
        <dt class="col-sm-2">
            @*@Html.DisplayNameFor(model => model.email)*@
            Email:
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.CarYear)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.CarYear)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.CarMake)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.CarMake)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.CarModel)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.CarModel)
        </dt>
        <dt class="col-sm-2">
            @*@Html.DisplayNameFor(model => model.city)*@
            City:
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.City)
        </dd>
        <dt class="col-sm-2">
            @*@Html.DisplayNameFor(model => model.state)*@
            State:
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.State)
        </dd>

    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new { CustomerId = Model.CustomerId}) |
    <a asp-action="Index">Back to List</a>
</div>

AutoPartsStore/AutoPartsStore/Views/Store/LoggedInLandingPage.cshtml
@{
    ViewData["Title"] = "LoggedInLandingPage";
}

@ViewData["Title"]

@ViewData["Welcome"]

@*buttons to view item list*@
<div>
    <button class="btn-outline-primary"><a class="btn" asp-area="" asp-controller="Store" asp-action="Create"></a>Create an account</button>
    <button class="btn-outline-secondary"><a class="btn" asp-area="" asp-controller="Store" asp-action="CustomerList">Login</a></button>

</div>

AutoPartsStore/AutoPartsStore/Views/Store/VerifyCreateCustomer.cshtml
@model ModelsLibrary.Customer

@{
    ViewData["Title"] = "VerifyCreateCustomer";
}

@*<h1>VerifyCreateCustomer</h1>
*@
<div>
    <h4>Verify New Customer Information</h4>
    <hr />
    <dl class="row">
        @*<dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CustomerId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CustomerId)
        </dd>*@
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.FirstName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.LastName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.LastName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.PhoneNumber)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.PhoneNumber)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.CarYear)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.CarYear)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.CarMake)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.CarMake)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.CarModel)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.CarModel)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.City)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.City)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.State)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.State)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Password)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Password)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Store)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Store)
        </dd>

    </dl>
</div>
<div>
    
    <a asp-controller="Home" asp-action="Index">Submit New Customer</a> |
    <a asp-action="Index">Back to List</a>
</div>